name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: your-username # Replace with your actual GitHub username
          outputs: |
            output/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Snake SVG
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add output/snake.svg
          git commit -m "Update snake.svg"
          git push
